import 'dart:convert';
import 'package:yaml/yaml.dart';
import '../core/logger/app_logger.dart';
import '../services/primitives/primitive_registry.dart';

/// Tool config generated by the AI — persisted as YAML.
class ToolConfig {
  final String name;
  final String description;
  final String category;
  final List<ToolParameter> parameters;
  final List<ToolStep> steps;
  final bool requiresApproval;
  final String? maxRate;
  final DateTime createdAt;

  const ToolConfig({
    required this.name, required this.description, required this.category,
    required this.parameters, required this.steps, this.requiresApproval = false,
    this.maxRate, required this.createdAt,
  });

  Map<String, dynamic> toJson() => {
    'name': name, 'description': description, 'category': category,
    'parameters': parameters.map((p) => p.toJson()).toList(),
    'steps': steps.map((s) => s.toJson()).toList(),
    'requires_approval': requiresApproval, 'max_rate': maxRate,
    'created_at': createdAt.toIso8601String(),
  };

  /// Convert to OpenAI-compatible function schema for LLM tool calling.
  Map<String, dynamic> toFunctionSchema() {
    final props = <String, dynamic>{};
    final required = <String>[];
    for (final p in parameters) {
      props[p.name] = {'type': p.type, 'description': p.description};
      if (p.required) required.add(p.name);
      if (p.enumValues != null) props[p.name]!['enum'] = p.enumValues;
    }
    return {
      'type': 'function',
      'function': {
        'name': name,
        'description': description,
        'parameters': {'type': 'object', 'properties': props, if (required.isNotEmpty) 'required': required},
      },
    };
  }

  /// Parse from YAML string (AI-generated).
  factory ToolConfig.fromYaml(String yamlStr) {
    final doc = loadYaml(yamlStr) as Map;
    return ToolConfig(
      name: doc['name'] as String,
      description: doc['description'] as String,
      category: doc['category'] as String? ?? 'custom',
      parameters: (doc['parameters'] as Map?)?.entries.map((e) => ToolParameter(
        name: e.key.toString(), type: (e.value is Map ? (e.value['type'] ?? 'string') : 'string').toString(),
        description: (e.value is Map ? e.value['description'] : '')?.toString() ?? '',
        required: (e.value is Map ? e.value['required'] : false) == true,
        enumValues: (e.value is Map && e.value['enum'] != null) ? (e.value['enum'] as List).cast<String>() : null,
      )).toList() ?? [],
      steps: (doc['steps'] as List?)?.map((s) {
        final step = s as Map;
        return ToolStep(primitive: step['primitive'] as String, args: Map<String, dynamic>.from(step['args'] as Map? ?? {}));
      }).toList() ?? [],
      requiresApproval: doc['safety']?['requires_approval'] == true,
      maxRate: doc['safety']?['max_rate']?.toString(),
      createdAt: DateTime.now(),
    );
  }
}

class ToolParameter {
  final String name, type, description;
  final bool required;
  final List<String>? enumValues;
  const ToolParameter({required this.name, this.type = 'string', this.description = '', this.required = false, this.enumValues});
  Map<String, dynamic> toJson() => {'name': name, 'type': type, 'description': description, 'required': required, if (enumValues != null) 'enum': enumValues};
}

class ToolStep {
  final String primitive;
  final Map<String, dynamic> args;
  const ToolStep({required this.primitive, required this.args});
  Map<String, dynamic> toJson() => {'primitive': primitive, 'args': args};
}

/// Evolution Engine — enables AI to learn, create, and deploy new capabilities.
class EvolutionEngine {
  final AppLogger _logger = AppLogger();
  final PrimitiveRegistry _primitives;
  final List<ToolConfig> _tools = [];

  EvolutionEngine({required PrimitiveRegistry primitives}) : _primitives = primitives;

  List<ToolConfig> get tools => List.unmodifiable(_tools);
  List<Map<String, dynamic>> get functionSchemas => _tools.map((t) => t.toFunctionSchema()).toList();

  /// Register a pre-built tool.
  void registerTool(ToolConfig tool) {
    _tools.removeWhere((t) => t.name == tool.name);
    _tools.add(tool);
    _logger.info('Tool registered: ${tool.name}');
  }

  /// AI generates a tool config → validate → register.
  Future<ToolConfig> evolveFromYaml(String yamlStr) async {
    final tool = ToolConfig.fromYaml(yamlStr);
    // Validate that all primitives exist
    for (final step in tool.steps) {
      if (_primitives.get(step.primitive) == null) {
        throw EvolutionException('Unknown primitive: ${step.primitive}. Available: ${_primitives.all.map((p) => p.name).join(", ")}');
      }
    }
    registerTool(tool);
    return tool;
  }

  /// Execute a tool by name.
  Future<PrimitiveResult> executeTool(String toolName, Map<String, dynamic> args) async {
    final tool = _tools.firstWhere((t) => t.name == toolName, orElse: () => throw EvolutionException('Tool not found: $toolName'));
    return _executeSteps(tool.steps, args);
  }

  /// Execute steps sequentially, resolving template variables.
  Future<PrimitiveResult> _executeSteps(List<ToolStep> steps, Map<String, dynamic> args) async {
    final context = Map<String, dynamic>.from(args);
    PrimitiveResult? lastResult;

    for (final step in steps) {
      final primitive = _primitives.get(step.primitive);
      if (primitive == null) return PrimitiveResult(success: false, error: 'Unknown primitive: ${step.primitive}');

      // Resolve template variables: {args.xxx} or {prev.data.xxx}
      final resolved = _resolveVars(step.args, context, lastResult);
      lastResult = await primitive.execute(resolved);
      if (!lastResult.success) return lastResult;
    }

    return lastResult ?? PrimitiveResult(success: true, data: 'No steps executed');
  }

  Map<String, dynamic> _resolveVars(Map<String, dynamic> template, Map<String, dynamic> args, PrimitiveResult? prev) {
    final result = <String, dynamic>{};
    for (final entry in template.entries) {
      var value = entry.value;
      if (value is String) {
        value = value.replaceAllMapped(RegExp(r'\{([^}]+)\}'), (m) {
          final path = m.group(1)!;
          if (path.startsWith('args.')) return args[path.substring(5)]?.toString() ?? '';
          if (path.startsWith('prev.')) return prev?.data?.toString() ?? '';
          return m.group(0)!;
        });
      }
      result[entry.key] = value;
    }
    return result;
  }
}

class EvolutionException implements Exception {
  final String message;
  const EvolutionException(this.message);
  @override String toString() => 'EvolutionException: $message';
}
