import '../core/logger/app_logger.dart';

/// A single dimension of the user's personal profile.
class ProfileDimension {
  final String id;
  final String name;
  final String category; // physical, career, knowledge, social, mental, financial, lifestyle
  int score; // 0-100
  double weight; // importance weight
  DateTime lastUpdated;

  ProfileDimension({
    required this.id, required this.name, required this.category,
    this.score = 50, this.weight = 1.0,
  }) : lastUpdated = DateTime.now();

  Map<String, dynamic> toJson() => {
    'id': id, 'name': name, 'category': category,
    'score': score, 'weight': weight, 'last_updated': lastUpdated.toIso8601String(),
  };
}

/// A goal or plan generated by the AI.
class DevelopmentPlan {
  final String id;
  final String title;
  final String description;
  final String category;
  final List<PlanStep> steps;
  final double progress; // 0.0 - 1.0
  final DateTime createdAt;
  final DateTime? targetDate;

  const DevelopmentPlan({
    required this.id, required this.title, required this.description,
    required this.category, required this.steps,
    this.progress = 0.0, required this.createdAt, this.targetDate,
  });
}

class PlanStep {
  final String title;
  final String? detail;
  bool completed;
  PlanStep({required this.title, this.detail, this.completed = false});
}

/// Tracks user personal development across multiple dimensions.
/// AI uses this to suggest improvement plans and track progress.
class PersonalDevelopmentService {
  final AppLogger _logger = AppLogger();
  final List<ProfileDimension> _dimensions = [];
  final List<DevelopmentPlan> _plans = [];

  // --- Dimensions ---

  void initDefaultDimensions() {
    if (_dimensions.isNotEmpty) return;
    for (final d in [
      ProfileDimension(id: 'fitness', name: '身体素质', category: 'physical', weight: 1.0),
      ProfileDimension(id: 'appearance', name: '外表形象', category: 'physical', weight: 0.8),
      ProfileDimension(id: 'knowledge', name: '知识水平', category: 'knowledge', weight: 1.2),
      ProfileDimension(id: 'career', name: '职业竞争力', category: 'career', weight: 1.5),
      ProfileDimension(id: 'social', name: '社交能力', category: 'social', weight: 0.9),
      ProfileDimension(id: 'mental', name: '心理健康', category: 'mental', weight: 1.0),
      ProfileDimension(id: 'lifestyle', name: '生活习惯', category: 'lifestyle', weight: 1.1),
      ProfileDimension(id: 'finance', name: '财务健康', category: 'financial', weight: 1.0),
    ]) { _dimensions.add(d); }
  }

  List<ProfileDimension> get dimensions => List.unmodifiable(_dimensions);

  void updateScore(String dimensionId, int score) {
    final d = _dimensions.firstWhere((d) => d.id == dimensionId);
    d.score = score.clamp(0, 100);
    d.lastUpdated = DateTime.now();
  }

  /// Calculate overall "perfection score" weighted by user-defined importance.
  double get overallScore {
    if (_dimensions.isEmpty) return 0;
    var totalWeight = 0.0, weightedSum = 0.0;
    for (final d in _dimensions) {
      totalWeight += d.weight;
      weightedSum += d.score * d.weight;
    }
    return totalWeight > 0 ? (weightedSum / totalWeight).clamp(0.0, 100.0) : 0.0;
  }

  /// Get trend direction for a dimension (requires history — stub for now).
  String getTrend(String dimensionId) {
    return '→'; // Will track history in Phase 2
  }

  // --- Plans ---

  List<DevelopmentPlan> get plans => List.unmodifiable(_plans);

  void addPlan(DevelopmentPlan plan) => _plans.add(plan);

  void completeStep(String planId, int stepIndex) {
    final plan = _plans.firstWhere((p) => p.id == planId);
    if (stepIndex < plan.steps.length) {
      plan.steps[stepIndex].completed = true;
    }
  }

  /// Generate a summary for the AI system prompt.
  String getProfileSummary() {
    if (_dimensions.isEmpty) return '';
    final parts = <String>[
      '## 用户画像',
      '综合得分: ${overallScore.toStringAsFixed(1)}',
      ..._dimensions.map((d) => '- ${d.name}: ${d.score} (权重 ${d.weight})'),
      if (_plans.isNotEmpty) '\n## 活跃计划',
      ..._plans.where((p) => p.progress < 1.0).map((p) => '- ${p.title}: ${(p.progress * 100).toInt()}%'),
    ];
    return parts.join('\n');
  }
}
